---

  - name: Creation exception file ssh
    become: yes
    file: 
      path: /etc/ssh/two-factor-skip.conf  
      state: touch
      
  - name: Authorization rights ssh
    blockinfile:
      path: /etc/ssh/two-factor-skip.conf
      marker: "# {mark} SSH USER"
      state: present
      insertafter: EOF
      block: |
       # В локальной сети ходим только лишь с ключём
       #+ : ALL : 192.168.156.0/22
       # Этот юзер не может вводить одноразовые коды
       + : user : ALL
       # Всех остальных заставим вводить ещё и одноразовый код
       - : ALL : ALL
    notify: reload ssh  

  - name: Configure MFA On SSH Service
    blockinfile:
      path: /etc/ssh/sshd_config
      marker: "# {mark} MFA Configuration"
      state: present
      insertafter: EOF
      block: |
        AuthenticationMethods publickey keyboard-interactive
    notify: reload ssh
  
  - name: Configure MFA On SSH Service
    blockinfile:
      path: /home/{{ main_user_name }}/.bashrc
      marker: "# {mark} Add change qrcode"
      state: present
      insertafter: EOF
      block: |
        /usr/bin/google-authenticator 

  - name: Generate a timed-based,  reuse, rate-limited (3 logins per 30 seconds) with one concurrently valid code for default user
    command: /usr/bin/sed -i '$ d' /home/$USER/.bashrc
    become: yes
    become_user: "{{ main_user_name }}"
    become_method: sudo

...
