#!/bin/bash


filename="/home/ubuntu/Engineer-s-SOC/group_vars/srv_ansible.yaml"



user=$(head -n 3 /home/ubuntu/Engineer-s-SOC/group_vars/srv_ansible.yaml | tail -n1 | cut -f 1,2 -d ' ')
group=$(head -n 4 /home/ubuntu/Engineer-s-SOC/group_vars/srv_ansible.yaml | tail -n1 | cut -f 1,2 -d ' ')


# Добавить пользователя
read -p "Какого пользователя добавить?($user) : " replace_user

# Добавить группу
read -p "В какую группу добавить пользователя?($group) : " replace_group

# Отключить 2HA
read -p "Отключить 2HA (1)
Если не требуеться (2) 
: " replace_turn

# Запустить процесс для нового пользователя, или выключение для пользователя 2HA 
read -p "Если запустить процесс отключения 2HA для определенного пользователя наберите (1)
Если запустить процесс для нового пользователя набирите (2)
: " replace_process


on="publickey,keyboard-interactive"
off="publickey keyboard-interactive"


if [[ $user != "" && $replace_user != "" ]];  then
sed -i "s/$user/main_user_name: $replace_user/" /home/ubuntu/Engineer-s-SOC/group_vars/srv_ansible.yaml
fi

if [[ $group != "" && $replace_group != "" ]]; then
sed -i "s/$group/mygroup: $replace_group/" /home/ubuntu/Engineer-s-SOC/group_vars/srv_ansible.yaml
fi

if [ "yes" == "$replace_turn" ]; then
sed -i "s/$off/$on/" $fileadmin
elif [ "1" != "$replace_turn" ]; then
echo "!!!Действие невено, повторите. "
fi

if [ "2" == "$replace_process" ]; then
ansible-playbook goaut.yml -b -kk
elif [ "1" ==  "$replace_process" ]; then
ansible-playbook admin.yml -b -kk
else echo "Действие невено, повторите. "
fi



