---
- block:
  - name: Add group  
    become: yes
    group:
      name: "{{ mygroup }}"
      state: present

  - name: Add user 
    become: yes
    user:
      name: "{{ main_user_name }}"
      password: "{{ upassword | password_hash('sha512') }}"
      state: present
      shell: /bin/bash
      home: /home/{{ main_user_name }}
      group: "{{ mygroup }}"
      groups:
      - users

  - name: Creation file sudo.d
    become: yes
    file: 
      path: /etc/sudoers.d/{{ main_user_name }}  
      state: touch
      
  - name: User rights sudo 
    blockinfile:
      path: /etc/sudoers.d/{{ main_user_name }}
      marker: "# {mark} Sudo User"
      state: present
      insertafter: EOF
      block: |
         {{ main_user_name }} ALL=(ALL) NOPASSWD:/usr/sbin/useradd,/usr/sbin/userdel,/usr/sbin/usermod,/var/log/syslog,/etc/ssh/two-factor-skip.conf

  - name: Creation Dir SSH
    become: yes 
    file:
       path: /home/{{ main_user_name }}/.ssh
       mode: 0755
       state: directory

  - name: Copy script admin access_2ha.sh
    synchronize:
      src: ./access_2ha.sh
      dest: /home/{{ administrator }}/

  - name: Copy script access_2ha
    become: yes
    copy:
       src: ./access_2ha.sh
       dest: /home/{{ main_user_name }}/
       mode: 0777
       remote_src: yes

  - name: Rights to syslog
    become: yes
    file:
       path: /var/log/syslog
       mode: 0666


  - name: Copy file authorized_keys
    become: yes
    copy:
       src: /home/{{ administrator }}/.ssh/authorized_keys
       dest: /home/{{ main_user_name }}/.ssh/authorized_keys
       mode: 0644
       remote_src: yes

  - name: Install Google Authenticator PAM Module
    apt:
      name: libpam-google-authenticator
      update_cache: yes
      cache_valid_time: 86400
      state: present

  - name: Creation exception file ssh
    become: yes
    file:
      path: /etc/ssh/two-factor-skip.conf
      state: touch

  - name: Authorization rights ssh
    blockinfile:
      path: /etc/ssh/two-factor-skip.conf
      marker: "# {mark} SSH USER"
      state: present
      insertafter: EOF
      block: |
       # В локальной сети ходим только лишь с ключём
       #+ : ALL : 192.168.156.0/22
       # Этот юзер не может вводить одноразовые коды
       + : {{ administrator }} : ALL
       # Всех остальных заставим вводить ещё и одноразовый код
       - : ALL : ALL
    notify: reload ssh

  - name: Configure PAM Authentication Module
    lineinfile:
      path: /etc/pam.d/sshd
      regexp: '^@include common-auth'
      line: "#@include common-auth"
      state: present
      backrefs: yes
    notify: reload ssh

  - name: Enable Google Autnenticator PAM Module
    blockinfile:
      path: /etc/pam.d/sshd
      marker: "# {mark} Google Authenticator"
      state: present
      insertafter: EOF
      block: |
        auth       sufficient   pam_access.so accessfile=/etc/ssh/two-factor-skip.conf
        auth required pam_google_authenticator.so nullok
    notify: reload ssh

  - name: Configure SSHD Service For 2FA
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^ChallengeResponseAuthentication'
      line: "ChallengeResponseAuthentication yes"
      state: present
      backrefs: yes
    notify: reload ssh

  - name: Enable PAM In SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^UsePAM'
      line: "UsePAM yes"
      state: present
      backrefs: yes
    notify: reload ssh
  
  - name: Configure MFA On SSH Service
    blockinfile:
      path: /etc/ssh/sshd_config
      marker: "# {mark} MFA Configuration"
      state: present
      insertafter: EOF
      block: |
        AuthenticationMethods {{ path }}
    notify: reload ssh
  
  - name: "Check if .google_authenticator exists"
    stat:
     path: /home/{{ main_user_name }}/.google_authenticator
    register: check_google

  - name: Generate a timed-based,  reuse, rate-limited (3 logins per 30 seconds) with one concurrently valid code for default user
    command: /usr/bin/google-authenticator -t -f -d --qr-mode=UTF8 -r 3 -R 30 -w 1 --secret=/home/{{ main_user_name }}/.google_authenticator
    become: yes
    become_user: "{{ main_user_name }}"
    become_method: sudo
    notify: reload ssh
    when: not check_google.stat.exists  

  - name: Print to screen google authenticator details
    command: /usr/bin/cat /home/{{ main_user_name }}/.google_authenticator
    register: details
    become: yes

  - debug: msg="!!!COPY YOUR SECRET KEYS!!!  {{ details.stdout_lines | quote }}"

  - name: Add script`s to file profile
    blockinfile:
      path: /home/{{ main_user_name }}/.profile
      marker: "# {mark} Add change profile"
      state: present
      insertafter: EOF
      block: |
        ./access_2ha.sh
  
  - name: Open 22 port firewall
    ufw:
     rule: limit
     port: ssh
     proto: tcp

  when:
    - ansible_facts['architecture'] == 'x86_64'
    - ansible_facts['distribution'] == 'Ubuntu'
  become: yes
...
